<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DocumentRequest;

class DocumentRequestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $requests = [
            [
                'request_title' => 'Contract Renewal Documents',
                'description' => 'Need original contract documents for vendor renewal process. Include all amendments and addendums.',
                'priority' => 'High',
                'urgency' => 'Urgent (1-2 days)',
                'document_type' => 'Contract',
                'document_category' => 'Legal',
                'format_required' => 'Original Copy',
                'number_of_copies' => 2,
                'date_range' => 'Jan 2023 - Dec 2023',
                'reference_number' => 'VENDOR-2023-001',
                'notarization_required' => true,
                'apostille_needed' => false,
                'translation_required' => false,
                'certified_true_copy' => true,
                'delivery_method' => 'Office Pickup',
                'delivery_address' => 'Main Office, Document Room 101',
                'contact_person' => 'Sarah Johnson',
                'contact_number' => '+1-555-0123',
                'purpose' => 'Annual vendor contract renewal and compliance review',
                'project_name' => 'Vendor Management System',
                'cost_center' => 'CC-LEG-001',
                'status' => 'Under Review',
                'requested_by' => 'John Smith',
                'department' => 'Legal',
                'request_date' => '2026-02-05',
                'notes' => 'Please ensure documents are notarized before pickup',
            ],
            [
                'request_title' => 'Financial Audit Reports',
                'description' => 'Request for Q4 2023 financial statements and audit reports for board meeting.',
                'priority' => 'Critical',
                'urgency' => 'Critical (Same day)',
                'document_type' => 'Report',
                'document_category' => 'Financial',
                'format_required' => 'Digital Copy (PDF)',
                'number_of_copies' => 1,
                'date_range' => 'Oct 2023 - Dec 2023',
                'reference_number' => 'AUDIT-Q4-2023',
                'notarization_required' => false,
                'apostille_needed' => false,
                'translation_required' => false,
                'certified_true_copy' => false,
                'delivery_method' => 'Email Attachment',
                'delivery_address' => null,
                'contact_person' => 'Michael Chen',
                'contact_number' => '+1-555-0124',
                'purpose' => 'Board meeting presentation and investor relations',
                'project_name' => 'Q4 Board Meeting',
                'cost_center' => 'CC-FIN-002',
                'status' => 'Processing',
                'requested_by' => 'Emily Davis',
                'department' => 'Finance',
                'request_date' => '2026-02-06',
                'notes' => 'Send to board@company.com',
            ],
            [
                'request_title' => 'Employee Training Certificates',
                'description' => 'Need copies of all completed training certificates for compliance audit.',
                'priority' => 'Medium',
                'urgency' => 'Normal (3-5 days)',
                'document_type' => 'Certificate',
                'document_category' => 'HR',
                'format_required' => 'Scanned Copy',
                'number_of_copies' => 1,
                'date_range' => '2023 Annual',
                'reference_number' => 'HR-COMP-2023',
                'notarization_required' => false,
                'apostille_needed' => false,
                'translation_required' => false,
                'certified_true_copy' => false,
                'delivery_method' => 'Digital Download',
                'delivery_address' => null,
                'contact_person' => 'Lisa Wang',
                'contact_number' => '+1-555-0125',
                'purpose' => 'Annual compliance audit and training verification',
                'project_name' => 'Compliance Audit 2024',
                'cost_center' => 'CC-HR-003',
                'status' => 'Completed',
                'requested_by' => 'Robert Brown',
                'department' => 'HR',
                'request_date' => '2026-02-01',
                'notes' => 'All certificates have been uploaded to the portal',
            ],
            [
                'request_title' => 'Operating Licenses Renewal',
                'description' => 'Current business licenses and permits for renewal application.',
                'priority' => 'High',
                'urgency' => 'Urgent (1-2 days)',
                'document_type' => 'License',
                'document_category' => 'Operations',
                'format_required' => 'Certified Copy',
                'number_of_copies' => 3,
                'date_range' => 'Current Valid',
                'reference_number' => 'BIZ-LICENSE-2024',
                'notarization_required' => true,
                'apostille_needed' => true,
                'translation_required' => false,
                'certified_true_copy' => true,
                'delivery_method' => 'Courier Delivery',
                'delivery_address' => 'City Hall, Business License Division',
                'contact_person' => 'David Martinez',
                'contact_number' => '+1-555-0126',
                'purpose' => 'Business license renewal application submission',
                'project_name' => 'License Renewal 2024',
                'cost_center' => 'CC-OPS-004',
                'status' => 'Approved',
                'requested_by' => 'Jennifer Wilson',
                'department' => 'Operations',
                'request_date' => '2026-02-04',
                'notes' => 'Documents ready for courier pickup',
            ],
            [
                'request_title' => 'Technical Documentation',
                'description' => 'API documentation and technical specifications for client onboarding.',
                'priority' => 'Medium',
                'urgency' => 'Normal (3-5 days)',
                'document_type' => 'Report',
                'document_category' => 'Technical',
                'format_required' => 'Digital Copy (PDF)',
                'number_of_copies' => 1,
                'date_range' => 'Latest Version',
                'reference_number' => 'TECH-DOC-001',
                'notarization_required' => false,
                'apostille_needed' => false,
                'translation_required' => false,
                'certified_true_copy' => false,
                'delivery_method' => 'Email Attachment',
                'delivery_address' => null,
                'contact_person' => 'Alex Thompson',
                'contact_number' => '+1-555-0127',
                'purpose' => 'Client technical onboarding and integration',
                'project_name' => 'Client Integration Project',
                'cost_center' => 'CC-TECH-005',
                'status' => 'Draft',
                'requested_by' => 'Chris Anderson',
                'department' => 'Technical',
                'request_date' => '2026-02-07',
                'notes' => 'Waiting for final approval from technical lead',
            ],
        ];

        foreach ($requests as $request) {
            DocumentRequest::create($request);
        }
    }
}
