@extends('layouts.app')

@section('content')
<div class="container-fluid px-6 py-8">
    <!-- Breadcrumbs -->
    <nav class="flex mb-6" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-3">
            <li class="inline-flex items-center">
                <a href="{{ route('admin.dashboard') }}" class="text-gray-700 hover:text-blue-600 inline-flex items-center">
                    <i class='bx bx-home text-xl mr-2'></i>
                    Home
                </a>
            </li>
            <li>
                <div class="flex items-center">
                    <i class='bx bx-chevron-right text-gray-400'></i>
                    <a href="#" class="text-gray-700 hover:text-blue-600 ml-1 md:ml-2">Document Tracking</a>
                </div>
            </li>
            <li>
                <div class="flex items-center">
                    <i class='bx bx-chevron-right text-gray-400'></i>
                    <a href="{{ route('admin.documenttracking.reports') }}" class="text-gray-700 hover:text-blue-600 ml-1 md:ml-2">Reports</a>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <i class='bx bx-chevron-right text-gray-400'></i>
                    <span class="ml-1 text-gray-500 md:ml-2">Report Details</span>
                </div>
            </li>
        </ol>
    </nav>

    <!-- Page Header -->
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-gray-900">Report Details</h1>
        <div class="flex gap-3">
            @if(in_array($report->status, ['Processing', 'Scheduled']))
                <a href="{{ route('document-reports.edit', $report->id) }}" class="bg-orange-600 hover:bg-orange-700 text-white font-medium py-2 px-4 rounded-lg flex items-center gap-2 transition-colors">
                    <i class='bx bx-edit text-xl'></i>
                    Edit Report
                </a>
            @endif
            <a href="{{ route('admin.documenttracking.reports') }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium py-2 px-4 rounded-lg flex items-center gap-2 transition-colors">
                <i class='bx bx-arrow-back text-xl'></i>
                Back to Reports
            </a>
        </div>
    </div>

    <!-- Report Details -->
    <div class="bg-white rounded-lg shadow-sm border border-gray-200">
        <div class="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
            <h2 class="text-lg font-semibold text-gray-900">{{ $report->report_name }}</h2>
            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-{{ $report->status_color }}-100 text-{{ $report->status_color }}-800">
                {{ $report->status }}
            </span>
        </div>
        
        <div class="p-6">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <!-- Basic Information -->
                <div class="space-y-4">
                    <h3 class="text-md font-semibold text-gray-900">Basic Information</h3>
                    
                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            <p class="text-sm font-medium text-gray-500">Report Number</p>
                            <p class="text-sm text-gray-900">{{ $report->report_number }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">Report Type</p>
                            <p class="text-sm text-gray-900">{{ $report->report_type }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">Generated By</p>
                            <p class="text-sm text-gray-900">{{ $report->generated_by }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">Department</p>
                            <p class="text-sm text-gray-900">{{ $report->department }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">Report Date</p>
                            <p class="text-sm text-gray-900">{{ $report->report_date->format('M d, Y') }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">Created At</p>
                            <p class="text-sm text-gray-900">{{ $report->created_at->format('M d, Y H:i') }}</p>
                        </div>
                    </div>
                </div>

                <!-- Date Range -->
                @if($report->start_date || $report->end_date)
                <div class="space-y-4">
                    <h3 class="text-md font-semibold text-gray-900">Data Period</h3>
                    
                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            <p class="text-sm font-medium text-gray-500">Start Date</p>
                            <p class="text-sm text-gray-900">{{ $report->start_date ? $report->start_date->format('M d, Y') : 'N/A' }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">End Date</p>
                            <p class="text-sm text-gray-900">{{ $report->end_date ? $report->end_date->format('M d, Y') : 'N/A' }}</p>
                        </div>
                    </div>
                </div>
                @endif
            </div>

            <!-- Description -->
            @if($report->description)
            <div class="mt-6">
                <h3 class="text-md font-semibold text-gray-900 mb-3">Description</h3>
                <p class="text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">{{ $report->description }}</p>
            </div>
            @endif

            <!-- Parameters -->
            @if($report->parameters)
            <div class="mt-6">
                <h3 class="text-md font-semibold text-gray-900 mb-3">Parameters</h3>
                <p class="text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">{{ $report->parameters }}</p>
            </div>
            @endif

            <!-- Summary -->
            @if($report->summary)
            <div class="mt-6">
                <h3 class="text-md font-semibold text-gray-900 mb-3">Summary</h3>
                <p class="text-sm text-gray-700 bg-blue-50 p-4 rounded-lg border border-blue-200">{{ $report->summary }}</p>
            </div>
            @endif

            <!-- File Information -->
            @if($report->file_name)
            <div class="mt-6">
                <h3 class="text-md font-semibold text-gray-900 mb-3">File Information</h3>
                <div class="bg-gray-50 p-4 rounded-lg">
                    <div class="grid grid-cols-3 gap-4">
                        <div>
                            <p class="text-sm font-medium text-gray-500">File Name</p>
                            <p class="text-sm text-gray-900">{{ $report->file_name }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">File Size</p>
                            <p class="text-sm text-gray-900">{{ $report->file_size_in_mb }}</p>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-500">Actions</p>
                            <button class="text-blue-600 hover:text-blue-900 text-sm font-medium">
                                <i class='bx bx-download mr-1'></i>
                                Download
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            @endif

            <!-- Actions -->
            <div class="flex gap-3 mt-8 pt-6 border-t border-gray-200">
                @if(in_array($report->status, ['Processing', 'Scheduled']))
                    <a href="{{ route('document-reports.edit', $report->id) }}" class="bg-orange-600 hover:bg-orange-700 text-white font-medium py-2 px-6 rounded-lg transition-colors">
                        <i class='bx bx-edit mr-2'></i>
                        Edit Report
                    </a>
                @endif
                @if(in_array($report->status, ['Processing', 'Scheduled', 'Failed']))
                    <form action="{{ route('document-reports.destroy', $report->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this report?')" class="inline">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="bg-red-600 hover:bg-red-700 text-white font-medium py-2 px-6 rounded-lg transition-colors">
                            <i class='bx bx-trash mr-2'></i>
                            Delete Report
                        </button>
                    </form>
                @endif
                <a href="{{ route('admin.documenttracking.reports') }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium py-2 px-6 rounded-lg transition-colors">
                    <i class='bx bx-arrow-back mr-2'></i>
                    Back to Reports
                </a>
            </div>
        </div>
    </div>
</div>
@endsection
